### PR TITLE
Complete ice server url validation

### LINKED ISSUE #2912: Fix ICE server URL querystring validation
follow up to #2660: #2853 left a TODO: `validate ?transport=udp|tcp`

### PR DESCRIPTION
**Pull request by dontcallmedom**
close #2912

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-pc/pull/2996.html" title="Last updated on Oct 8, 2024, 7:16 AM UTC (22f85c4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-pc/2996/4888a48...22f85c4.html" title="Last updated on Oct 8, 2024, 7:16 AM UTC (22f85c4)">Diff</a>

### CODE REVIEW

**Comment by dontcallmedom** [comment]
(the CI error is because we don't have tests for this; as noted in #2950 this is only a continuation of the lack of test for this change; see also #2997)

**Comment by jan-ivar** [comment]
> ... reusing the application/x-www-form-urlencoded parser means making ?&transport=udp parsable

Less custom URL parsing seems in line with being _"consistent with how we treat URLs elsewhere in the platform."_. https://github.com/w3c/webrtc-pc/issues/2660#issuecomment-1494140703

> an alternative would be to instead do the split on `=` ourselves (rather than invoking the URL algorithm), limiting the set of acceptable query strings to `?transport=udp` and `?transport=tcp`

OTOH, if this simple string compare lets us keep this in REC, why not do that for now, and add application/x-www-form-urlencoded back in later?

That seems a reasonable way to increment here to me.

**Comment by dontcallmedom** [comment]
I've switched to using a simple string comparison; I'm not sure using `application/x-www-form-urlencoded` parsing buys us much when it is not clear the RFC means it that way.

**Comment by jan-ivar** [comment]
Yeah that algorithm supports multiple query parameters whereas our RFC does not, so it's arguably odd to support `&` at all

**Review by jan-ivar — APPROVED** [review]

**Pull request merged**
