### PR TITLE
getConfiguration should include all of RTCConfiguration

### PR DESCRIPTION
**Pull request by aboba**
Fix for Issue https://github.com/w3c/webrtc-pc/issues/813

### CODE REVIEW

**Comment by aboba** [comment]
@pthatcherg Does this address Issue 813?

**Comment by stefhak** [comment]
Alternative: store object in an internal slot.

**Comment by adam-be** [comment]
Can't we spec this as storing a copy of the input to `setConfiguration` in an internal slot, and then return that in `getConfiguration` (instead of taking it apart and assembling it again)

**Comment by aboba** [comment]
@stefhak  In addition to attributes set in setConfiguration or in the RTCPeerConnection constructor, there is the certificates attribute.  If this value is absent, then a set of certificates are generated for each RTCPeerConnection instance. As a result, getConfiguration().certificates may not return the same value as the RTCConfiguration passed in the RTCPeerConnection constructor (or in setConfiguration).

**Pull request closed without merging**
