### PR TITLE
pc.close() sets pc.signalingState to "closed"

### PR DESCRIPTION
**Pull request by aboba**
Fix for Issue https://github.com/w3c/webrtc-pc/issues/1367

### CODE REVIEW

**Comment by fippo** [comment]
In the operations section and other places we have `Set connection's signaling state to stable.` without saying its an attribute. I'd suggest s/attribute //

**Comment by aboba** [comment]
@fippo Fixed.

**Comment by aboba** [comment]
Issues https://github.com/w3c/webrtc-pc/issues/1288 and https://github.com/w3c/webrtc-pc/issues/1381 note that close() also doesn't close the SCTP transports or data channels.

**Comment by stefhak** [comment]
LGTM.

**Pull request merged**
