### PR TITLE
Make tone optional and constructor dictionary parameter optional

### PR DESCRIPTION
**Pull request by youennf**
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/webrtc-pc/pull/2413.html" title="Last updated on Dec 13, 2019, 9:52 AM UTC (bdd6349)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-pc/2413/affeeb2...youennf:bdd6349.html" title="Last updated on Dec 13, 2019, 9:52 AM UTC (bdd6349)">Diff</a>

### CODE REVIEW

**Comment by youennf** [comment]
WPT PR is at https://github.com/web-platform-tests/wpt/pull/20764

**Comment by youennf** [comment]
Testing on Chrome, it seems there is a small bug in the sense that the constructor expects one mandatory parameter but will reject if a second one is not provided.
This PR makes the second parameter optional, aligning with Firefox, Safari and consistent with other constructors in webrtc-pc

**Comment by youennf** [comment]
Fixes https://github.com/w3c/webrtc-pc/issues/2253

**Comment by henbos** [comment]
Approved, the next person taking a look, feel free to merge this if you also LGTM it

**Pull request merged**
