### PR TITLE
Specify the synchronous and queued steps for addIceCandidate (ver 2) (issue #600)

### PR DESCRIPTION
**Pull request by adam-be**
I abandoned PR #601 after the move to the new WebIDL style and the reformatting of the document. Otherwise, this is the same change.

### CODE REVIEW

**Comment by adam-be** [comment]
@jan-ivar, I've tried to address your comments from #601 in this new PR.

**Comment by adam-be** [comment]
Preview: http://rawgit.com/w3c/webrtc-pc/queued-operations-sync-2/webrtc.html#dom-peerconnection-addicecandidate

**Comment by jan-ivar** [comment]
Lgtm.

**Comment by adam-be** [comment]
Rebased

**Comment by aboba** [comment]
lgtm

**Pull request merged**
