### PR TITLE
Mention that codecs can be reordered or removed but not modified.

### LINKED ISSUE #1024: Need to describe that codecs can be removed or reordered, but not modified
We definitely decided on this, but I don't see it spelled out anywhere.

### PR DESCRIPTION
**Pull request by taylor-b**
Fixes #1024

### CODE REVIEW

**Comment by taylor-b** [comment]
This is meant to mean that the codec dictionaries can't be modified, and codecs can't be added. Hopefully that's clear enough.

**Comment by aboba** [comment]
@taylor-b How about this? 

Using the <code>setParameters</code> method, entries in the <code>codecs[]</code> sequence can be reordered or removed, but entries cannot be added, and <code><a>RTCRtpCodecParameters</a></code> dictionary attributes cannot be modified.

**Comment by taylor-b** [comment]
You're right about `setCodecPreferences`. Might as well handle that now. I assume it's correct to say that codecs passed into `setCodecPreferences` can only contain codecs that are returned by `RTCRtpSender.getCapabilities()` or `RTCRtpReceiver.getCapabilities()`.

**Comment by aboba** [comment]
@taylor-b Reading the PR, it seemed that setCodecPreferences has the same set of restrictions as setParameters() with respect to codecs.  Is that correct?  Is the only difference that setCodecPreferences can reorder or remove a codec from the SDP produced by createOffer/createAnswer (but not change the fmtp parameters), and sets negotiation-needed, whereas setParameters() never sets negotiation-needed and has no effect on the SDP produced by createOffer/createAnswer?

**Comment by taylor-b** [comment]
@aboba That sounds correct. The other difference is that "setCodecPreferences" can include receive-only codecs.

**Comment by aboba** [comment]
Based on the virtual discussion, this PR seems ready to merge.

**Pull request merged**
