### PR TITLE
Update map to IETF drafts

### PR DESCRIPTION
**Pull request by dontcallmedom**
Also, prepare spec for Rec updateability

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-pc/pull/2594.html" title="Last updated on Dec 16, 2020, 7:52 AM UTC (de4c91f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-pc/2594/9915912...de4c91f.html" title="Last updated on Dec 16, 2020, 7:52 AM UTC (de4c91f)">Diff</a>

### CODE REVIEW

**Comment by fluffy** [comment]
I don't disagree with the removal the Identity reference but it is sad to see the W3C care so little about privacy that this has all been removed.

**Comment by dontcallmedom** [comment]
for clarification, this pull request doesn't remove the reference to WebRTC identity, it only removes it from the local bibliography (which is no longer needed since WEBRTC-IDENTITY is now documented in specref)

**Comment by henbos** [comment]
There's a respec error pubsubpubsupbub bla can you take a look?

**Comment by dontcallmedom** [comment]
I think it can be safely ignored

**Comment by dontcallmedom** [comment]
overtaken by #2621

**Pull request closed without merging**
