### PR TITLE
Removing 'readonly' from Tranceiver's 'direction'.

### LINKED ISSUE #1747: Direction is not readonly
See https://w3c.github.io/webrtc-pc/#dom-rtcrtptransceiver-direction. "readonly" should be removed.

### PR DESCRIPTION
**Pull request by stefhak**
Close #1747

***
<a href="https://pr-preview.s3.amazonaws.com/stefhak/webrtc-pc/pull/1762.html" title="Last updated on Feb 2, 2018, 11:57 AM GMT (5cf3ddb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-pc/1762/d682ab2...stefhak:5cf3ddb.html" title="Last updated on Feb 2, 2018, 11:57 AM GMT (5cf3ddb)">Diff</a>

### CODE REVIEW

**Comment by alvestrand** [comment]
Is there a test that this will affect, or is it a test-less change?
(I think the IDL may be in there somewhere due to @foolip 's efforts. If so, that needs to change.)

**Comment by stefhak** [comment]
@foolip can you comment?
'readonly' was actually not in the IDL, only in the explaining text following the IDL (and that's where this PR removes it).

**Comment by foolip** [comment]
From some quick searching, it looks to me like there aren't any tests for setting `direction` on `RTCRtpTransceiver` instances at all, but there is this test:
https://wpt.fyi/webrtc/RTCRtpTransceiver-setDirection.html

But the `setDirection()` method was removed in https://github.com/w3c/webrtc-pc/pull/1647, which is probably also where the change happening in this PR was forgotten.

So test updates to match https://github.com/w3c/webrtc-pc/pull/1647 are needed, and this change is just cleanup following that.

**Comment by alvestrand** [comment]
Filed https://github.com/w3c/web-platform-tests/issues/9438 so as to not forget about #1647.

**Pull request merged**
