### PR TITLE
Document "test as you commit" policy in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by foolip**
At TPAC it was resolved to try this policy for webrtc-pc.

Fixes https://github.com/w3c/webrtc-pc/issues/1617.

### CODE REVIEW

**Comment by foolip** [comment]
The wording here is from https://github.com/WICG/feature-policy/pull/91, and https://github.com/foolip/testing-in-standards/blob/master/policy.md links to many others specs also using this wording.

**Comment by foolip** [comment]
@adam-be, will you take care of merging as well? I want to claim on Wednesday that WebRTC is doing this :)

**Comment by adam-be** [comment]
I'll try to get some more opinions, but let's aim for merging before Wednesday.

**Comment by adam-be** [comment]
I'm thinking about how all this will be done in practice. Probably I'll take an existing test, copy it and update it to do what I want. So, it would be really great to have some pointers to some of our tests that are really good examples of how tests should be written.

**Comment by foolip** [comment]
I think the very first test in order is quite good:
https://wpt.fyi/webrtc/RTCCertificate.html

There was a typo (https://github.com/w3c/web-platform-tests/pull/8087) but otherwise looks good to me, testing both things that should work and things that shouldn't.

I also like https://wpt.fyi/webrtc/RTCDataChannelEvent-constructor.html,  as an example of being pretty thorough with "boring" stuff like the difference between undefined and null in dictionaries.

In some of the existing tests you'll find large comment blocks. The group will have to judge if those are useful or not. I think @rwaldron and @soareschen used this extra bookkeeping to judge the spec coverage and produce https://rwaldron.github.io/webrtc-pc/, but it's definitely not a requirement generally in web-platform-tests. (Also, we basically have no idea about the test coverage in most areas.)

**Comment by burnburn** [comment]
@foolip I think this text is a fine start (meaning we can apply it and then modify if needed).  I have the same concerns @adam-be does regarding information we could present to those we ask to write tests for their PRs.  I think the contents of your comment right above this one would be a good start for a webrtc-pc specific informative testing doc that anyone can update it as they have more info to add that would help our group write tests.  @adam-be tells me he wants to create that (small) doc right before merging this PR, and I agree.

**Comment by foolip** [comment]
The other resources I would point to are:
http://web-platform-tests.org/writing-tests/index.html
http://web-platform-tests.org/reviewing-tests/index.html

**Pull request merged**
