### PR TITLE
Replace DOMError with DOMException

### LINKED ISSUE #335: DOMError is removed from the platform; use DOMException instead

### PR DESCRIPTION
**Pull request by dontcallmedom**
close #335

### CODE REVIEW

**Comment by burnburn** [comment]
This is not a pre-defined DOMException, and per the discussion on the gUM spec we are not allowed to add to the list of defined DOMException values.  We need to use a pre-defined one or define a new error object as in gUM.  Off the top of my head I don't know which pre-defined value would be appropriate.

**Comment by alvestrand** [comment]
Dan has promised to do a pass over the error handling to bring it in line with the (accepted) approach taken in getUserMedia. We'll hold this until that.

**Comment by dontcallmedom** [comment]
note that I have a pull request that goes over the errors to align them with existing error names: https://github.com/w3c/webrtc-pc/pull/472

**Comment by alvestrand** [comment]
RTCSdpError was intended as the result error from SDP failures in Set{local/remote}Description.
Is it gone from there?

**Comment by dontcallmedom** [comment]
it was never added there (error management has been marked at TBD in setLD and setRD for ever)

**Comment by dontcallmedom** [comment]
(I should say it's also telling that RTCSdpError was also never implemented, nor have we seen lots of complaints about it as far as I can tell)

**Comment by alvestrand** [comment]
Given the headaches that implementing the name field in ConstraintError gave me, I can't say that I'm eager to defend SDPError's continued existence.
Interim topic?

**Comment by dontcallmedom** [comment]
I think the case for SDPError is also weaker than ConstrainError, since it's very unlikely that anyone can take programmatic actions based on the line number where the error was detected in the SDP.

I'll bring it to the list (since after all that's part of the changes I'm proposing); depending on the reaction, making this an interim topic may or may not be needed.

**Comment by burnburn** [comment]
I understand now that all you are doing here is to rename DOMError to DOMException and then adjusting the individual errors in PR #472.  Merging.

**Comment by foolip** [comment]
Did you forget to push this to gh-pages? https://w3c.github.io/webrtc-pc/ doesn't include the fix and I spent time worrying about it in https://codereview.chromium.org/1661493002/ before finding this :(

**Comment by alvestrand** [comment]
We don't auto-push to gh-pages, only when publishing a new editors' draft (every few weeks).
The reasons for this are convoluted.

**Pull request merged**
