### PR TITLE
Fix for #224

### PR DESCRIPTION
**Pull request by fluffy**

### CODE REVIEW

**Comment by stefhak** [comment]
@juberti can you look at this one?

**Comment by stpeter** [comment]
It seems to me that Section 8.1.2 is the better text to reference:

http://tools.ietf.org/html/rfc5245#section-8.1.2

Section 8.3.1 is more about post-completion cleanup, IMHO.

**Comment by alvestrand** [comment]
@fluffy can you change the reference (or argue why it shouldn't be) and re-push, so that we can see if Travis turns green?

**Comment by fluffy** [comment]
I think this is ready to merge. Please review.

**Comment by juberti** [comment]
FWIW, "completed" on the controlled side is caused by either
a) receipt of USE-CANDIDATE (regular nom)
b) 3 seconds since last receipt of USE-CANDIDATE (aggressive nom)

**Pull request merged**
