### PR TITLE
Add RTCAnswerOptions.

### PR DESCRIPTION
**Pull request by pthatcherg**
Part of https://github.com/w3c/webrtc-pc/issues/128

### CODE REVIEW

**Comment by jesup** [comment]
LGTM

**Comment by stefhak** [comment]
This looks reasonable to me.

**Comment by stefhak** [comment]
Isn't this (VAD wanted to be off) something we should do on the RtpSender object instead? It seems to be associated with one track (of kind audio) to be sent over the network, and thus seems fitting to go into the RtpSender object to me.

**Comment by fluffy** [comment]
It's pretty likely that if you want to set it at all, you want it for everything on the PC. I'd prefer to have it an an option for creating offer / answer but I think it makes sense to *also* have it settable at a more fine grain level on the RtpSender.

**Comment by fluffy** [comment]
LGTM

**Comment by stefhak** [comment]
I remain unconvinced about this going inte SDP offer/answer options. This is something that the sender can control - no need to negotiate. And, there are codecs for which there is no SDP attributes to indicate "do not use VAD / DTX / CN" (AMR and AMR-WB). The natural place would be the RTPSender IMO.

**Comment by stefhak** [comment]
I was wrong.... my point was that using VAD or not really belongs to the RTPSender object. But that should not stop this PR to be merged - this PR is about allowing options also for the Answer, and we should do that. 
I'll open an Issue on my point.

**Pull request merged**
