### PR TITLE
editorial: fix indent of [Exposed=Window]

### PR DESCRIPTION
**Pull request by fippo**
image
looks ugly ;-)

***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-pc/pull/2573.html" title="Last updated on Sep 10, 2020, 3:07 PM UTC (96c1d6b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-pc/2573/0b40ccf...fippo:96c1d6b.html" title="Last updated on Sep 10, 2020, 3:07 PM UTC (96c1d6b)">Diff</a>

### CODE REVIEW

**Comment by dontcallmedom** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by fippo** [comment]
I wonder if that is a regression from #2569 in which case fixing it would be reverted again soon...

**Comment by fippo** [comment]
Looks like it. Updated to move to the previous line which hopefully should survive tidy-ing

**Comment by dontcallmedom** [comment]
I can also see if tidy can be tweaked to ignore `<pre>` in its indenting?

**Review by henbos — APPROVED** [review]

**Pull request merged**
