### PR TITLE
Add PeerConnection.onfatalerror and .onwarning.

### PR DESCRIPTION
**Pull request by pthatcherg**
As a possible solution to https://github.com/w3c/webrtc-pc/issues/278

### CODE REVIEW

**Comment by juberti** [comment]
Can you give some examples of when either would be fired?

What constitutes 'fatal'? Isn't that really the app's decision (e.g. if audio broke but video did not)?

**Comment by pthatcherg** [comment]
I think fatal means "you might as well close down the PeerConnection".  The
initial scenario that get me writing this PR is
https://github.com/w3c/webrtc-pc/issues/278, where SRTP fails to
initialize.  If we have an aggregate DTLS or DTLS+ICE state, then we might
not need it to be fatal, since setting the state to "failed" would
effectively do the same thing.

On maybe that's an argument against having an a fatal event: if it's fatal,
set aggregate state to "failed" and just provide a diagnostic message.

**Comment by martinthomson** [comment]
This needs to be a lot more precise.  I think that by now we should know exactly what conditions are "fatal" and what requires warnings.

**Comment by pthatcherg** [comment]
I didn't call it a strawman for nothing :).

So here's a question:  if we ditch the "onfatalerror" and just had
"onwarning", would that valuable by itself just to have a way of sending
diagnostic messages to the JS?

**Comment by juberti** [comment]
Unless we have examples, I'm not sure.

I don't think it's reasonable to try to report browser bugs (e.g. SRTP fail) to the application. What should it do with them? 
Better to use UMA or similar mechanisms.

**Comment by pthatcherg** [comment]
Would your TURN error you were mentioning before be an example?  Or did you
have something else in mind for handling it?

**Comment by juberti** [comment]
No, TURN errors are handled by #284

**Comment by alvestrand** [comment]
Closing per Seattle discussions - not needed.

**Pull request closed without merging**
