### PR TITLE
Reserve and use RangeError for scaleResolutionDownBy < 1.0.

### PR DESCRIPTION
**Pull request by jan-ivar**
Fix for https://github.com/w3c/webrtc-pc/issues/493.

### CODE REVIEW

**Comment by jan-ivar** [comment]
I left the MUST language under scaleResolutionDownBy alone, as the whole text there talks about what will happen (talking to the user rather than the implementer), which seems to be a problem/reality throughout.

**Comment by jan-ivar** [comment]
@adam-be would you mind taking a look at this one?

**Comment by aboba** [comment]
LGTM.

**Comment by stefhak** [comment]
LGTM

**Pull request merged**
