### PR TITLE
Remove duration and interToneGap attributes

### PR DESCRIPTION
**Pull request by aboba**
Fix for Issue https://github.com/w3c/webrtc-pc/issues/843

### CODE REVIEW

**Comment by rshpount** [comment]
Should toneBuffer be an array with DTMF tone, tone duration and subsequent gap? This way insertDTMF method would store desired tones with their duration and gap in toneBuffer and DTMF playback algorithm will play each tone based on the timing information stored for each tone. Otherwise it looks like you can adjust the duration of currently playing on un-played tones by calling insertDTMF.

**Comment by aboba** [comment]
@rshpount Based on this PR, the duration and interToneGap arguments are used within the queued playout task, rather than the attributes.  So it appears to me that calling:

insertDTMF("bbbbb",  100, 70)
insertDTMF("111", 6000, 100)

could not cause "B" tones to be played with a duration of 6 seconds (e.g. the second insertDTMF call will queue a playout task that will execute after the first one).

**Comment by rshpount** [comment]
@aboba This PR is ambiguous since in case

insertDTMF("bbbbb", 100, 70)
insertDTMF("111", 6000, 100)

It is unclear which value of duration and interToneGap parameters are referenced in the Playout task.

It would be cleaner to state that duration and interToneGap parameter values are stored for each tone by insertDTMF and these values are used by the Playout task. It means that internal state of the RTCDTMFSender is not toneBuffer string, but an array of tones with tone name, duration and interToneGap stored for each of them. If this is the internal state, then this is the data that should be exposed.

**Comment by martinthomson** [comment]
If I call `insertDTMF("1", 100, 100)` then `insertDTMF("2", 200, 200)`, I agree with @rshpount that the "1" should play for 100ms and the "2" should play for 200ms, but what is the gap between the two?  (i.e., is the inter-tone gap a leading (`gapBefore2 = nextTone.gap`), trailing (`gapBefore = lastTone.gap`) or combinatorial property (`gapBefore2 = Math.max(lastTone.gap, nextTone.gap)`; see CSS margins for an example of this in practice).

**Comment by alvestrand** [comment]
It's clear that people have problems reading the algorithm. Removing the attributes makes the text describing the algorithm simpler. So this change seems good.

**Comment by rshpount** [comment]
The algorithm was clearer with the attributes, but it was saying the wrong thing (subsequent insertDTMF updates the duration and interToneGap attributes, which are used for the playback of queued tones, including tones queued by the previous insertDTMF). Without attributes it is unclear which duration and interToneGap values are used for tone playback.

I agree that attribute removal is a good thing, but should we create another issue about the playback algorithm? I think fixing the playback algorithm might affect the attribute exposed by RTCDTMFSender.

**Comment by alvestrand** [comment]
@rshpount you missed the part where insertDTMF will clear the tone buffer.
It can never modify playback on previous tones, because the previous tones are either being played already, or they are cleared.

**Comment by rshpount** [comment]
@alvestrand You are correct that I missed that insertDTMF resets or clears the buffer. The only thing to be might need to be clarified is that tone which is currently being played when new insertDTMF is called is followed up by the interToneGap from the insertDTMF call that queued the tone, not any of the subsequent ones.

**Pull request merged**
