### PR TITLE
Add RTCSessionDescriptionReadOnly to make RTCSessionDescription membe…

### PR DESCRIPTION
**Pull request by jan-ivar**
…rs writable again for webcompat.

Fix for https://github.com/w3c/webrtc-pc/issues/933.

### CODE REVIEW

**Comment by foolip** [comment]
The pattern I've seen in https://drafts.fxtf.org/geometry/ and some other places is InterfaceNameReadOnly.

How certain can we be that no content depends on being able to change type or sdp on localDescription, remoteDescription and similar? Per https://github.com/w3c/webrtc-pc/issues/573#issuecomment-259206448 it sounds like changing them does nothing in Edge, is that also true in Gecko?

**Comment by jan-ivar** [comment]
Certain.

Firefox and Chrome return no-op copies too (`pc.localDescription == pc.localDescription` is false).

Setting these is what the methods `setLocalDescription` and `setRemoteDescription` are for.

**Comment by alvestrand** [comment]
This is a breaking change for all code that uses the attribute names. We need to argue that the benefit outweights the cost.

**Comment by foolip** [comment]
> Firefox and Chrome return no-op copies too (`pc.localDescription == pc.localDescription` is false).

Oh, that's too bad. That doesn't seem per spec, do you intent to change the spec or hope to match it? I assume match it, since otherwise it wouldn't be useful to make the return value readonly?

**Comment by jan-ivar** [comment]
@foolip I have a patch for Firefox that fixes `pc.localDescription == pc.localDescription`.

@alvestrand What do you mean "code that uses the attribute names"? Can you give an example?

**Comment by alvestrand** [comment]
the other one looks better.

**Comment by jan-ivar** [comment]
@alvestrand Note that https://github.com/w3c/webrtc-pc/issues/949 only fixes the legacy callbacks, which was a regression, so thanks for merging it, just note it doesn't in itself address https://github.com/w3c/webrtc-pc/issues/933 which was about someone doing this:

```js
({type, offer}) => {
  var desc = new RTCSessionDescription({type});
  desc.sdp = sdp; // now silently ignored
  var desc = pc.setLocalDescription(desc);
}
```

rather than

```js
({type, offer}) => pc.setLocalDescription(new RTCSessionDescription({type, offer}))
```

Maybe no-one does that, but I could see it causing pain if someone modified sdp this way, and everything worked except the modification didn't take. But perhaps this breakage pales in comparison to the spec apparently deciding to no longer allowing sdp modifications of any kind, so I'm fine either way, just so we're on the same page.

**Comment by alvestrand** [comment]
This particular example wouldn't work anyway, due to the "unchanged string" requirement, but it's relevant for "pc.setRemoteDescription".

Note - setLocalDescription() takes an RTCSessionDescriptionInit. I assume that the serializer in RTCSessionDescription means that it autoconverts to an RTCSessionDescriptionInit-compatible dictionary when passed to setLocalDescription - otherwise we'd already have broken the web.

"pc.setRemoteDescription({type, offer})" should Just Work, right?

**Pull request closed without merging**
