### PR TITLE
Improve markup for events definitions

### PR DESCRIPTION
**Pull request by dontcallmedom**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-pc/pull/2595.html" title="Last updated on Feb 15, 2021, 7:55 AM UTC (c824e8a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-pc/2595/60f2135...c824e8a.html" title="Last updated on Feb 15, 2021, 7:55 AM UTC (c824e8a)">Diff</a>

### CODE REVIEW

**Comment by dontcallmedom** [comment]
pending https://github.com/w3c/respec/issues/3197

**Comment by henbos** [comment]
Did you want to merge this?

**Comment by dontcallmedom** [comment]
this is still pending progress on w3c/respec#3197 - I'll remove the draft status when ready to merge

**Comment by alvestrand** [comment]
https://github.com/w3c/respec/issues/3197 is now closed. @dontcallmedom ?

**Comment by dontcallmedom** [comment]
with #2626 merged, this now is ready to merge

**Review by youennf — APPROVED** [review]

**Pull request merged**
