### PR TITLE
Clarifying how setConfiguration checks certificate values

### PR DESCRIPTION
**Pull request by youennf**
Certificate comparison is based on JS ===.
The order of the certificates in the sequence is insignificant.

***
<a href="https://pr-preview.s3.amazonaws.com/youennf/webrtc-pc/pull/2113.html" title="Last updated on Mar 14, 2019, 4:32 AM UTC (9a7217a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-pc/2113/76a6464...youennf:9a7217a.html" title="Last updated on Mar 14, 2019, 4:32 AM UTC (9a7217a)">Diff</a>

### CODE REVIEW

**Comment by youennf** [comment]
Related issue is https://github.com/w3c/webrtc-pc/issues/2043

**Comment by lgrahl** [comment]
It may make sense to also replace the term *set* with *sequence*.

**Comment by youennf** [comment]
> It may make sense to also replace the term _set_ with _sequence_.

Agreed it is strange that iceServers is defined as an array and certificates as a set while they are both WebIDL sequences. 'list' seems to be used a lot in the spec, so maybe that should be the term we use for both.

**Comment by henbos** [comment]
Check the order

**Comment by aboba** [comment]
@youennf What about checking the order?

**Pull request merged**
