### PR TITLE
FrozenArray for interface, sequence for dictionary

### LINKED ISSUE #251: Update RTCTrackEvent to use FrozenArray<>
s/MediaStream[]/FrozenArray<MediaStream>/

http://www.w3.org/mid/BLUPR03MB38939AF0981AFF796FE3640F8990@BLUPR03MB389.namprd03.prod.outlook.com

### PR DESCRIPTION
**Pull request by martinthomson**
Closes #251, though there is no indication that this hasn't regressed in other places.

### CODE REVIEW

**Comment by martinthomson** [comment]
This will, of course, fail on Travis.

**Comment by martinthomson** [comment]
Which is of course no excuse for getting them back-to-front.

**Comment by dontcallmedom** [comment]
https://github.com/w3c/respec/pull/524 will fix the Travis error

**Comment by dontcallmedom** [comment]
Travis now happy again

**Pull request merged**
