### PR TITLE
Table of RTCRtpEncodingParameters for RtpSender/RtpReceiver

### PR DESCRIPTION
**Pull request by aboba**
Related to Issue https://github.com/w3c/webrtc-pc/issues/622
Partial fix for Issue https://github.com/w3c/webrtc-pc/issues/609

Rebase of PR https://github.com/w3c/webrtc-pc/pull/629

### CODE REVIEW

**Comment by mparis** [comment]
Hello @aboba,
from my point of view, the issue #622 is not fixed with this PR.
There, I meant how we can specify some parameters interesting for receiving like:

-     Max recv bandwidth (exposed in the SDP as "b=AS:X")
-     Congestion Control options
-     JitterBuffer configuration like minSize, maxSize, etc.
-     etc.

In the table I do not see them, even the maxBitrate is only for RtpSender.

Reading discuss-webrtc we can see that they are demanded, and as implementer I have the need of exposing them to allow the developer to configure the internal behaviour.

Best!!

**Comment by aboba** [comment]
@mparis Agree that this PR only clarifies what the currently specification does and does not support.

**Comment by stefhak** [comment]
Adding a table such as this is helpful IMO (I've not carefully reviewed its content though but I trust you @aboba !)

**Comment by mparis** [comment]
@aboba, if it is related with the **current** spec I agree with you,
but we shouldn't say that this fixes the issue #622, should we?

**Comment by aboba** [comment]
@mparis Sure - Changed description to say "Related to Issue https://github.com/w3c/webrtc-pc/issues/622"

**Comment by pthatcherg** [comment]
I like the table, but why not have .ssrc and .rid be in the Receiver parameters as well?

**Comment by aboba** [comment]
@pthatcherg Added .ssrc and .rid to the Receiver parameters.

**Pull request merged**
