### PR TITLE
Using DOMTimestamp for RTCCertificate::expires

### LINKED ISSUE #324: Let RTCCertificate.expires have type DOMTimeStamp
http://w3c.github.io/webrtc-pc/#rtccertificate-interface

Is it the intention that this attribute return the same object every time, or a new object every time? It is generally frowned upon to have APIs where `obj.attr==obj.attr` doesn't hold true, so using `[SameObject]` would be most neutral choice here.

### PR DESCRIPTION
**Pull request by martinthomson**
Closes #324

### CODE REVIEW

**Comment by jan-ivar** [comment]
two words, really? https://en.wikipedia.org/wiki/Timestamp

**Comment by alvestrand** [comment]
@martinthomson it seems you changed the mode of every file as a side effect.
Can you back out and try again?

**Comment by martinthomson** [comment]
Damn, I didn't even notice.  I hate it how git on windows does that.

**Comment by alvestrand** [comment]
Now it looks good!

**Pull request merged**
