### PR TITLE
TypeError unless all or none of encodings have rids

### LINKED ISSUE #2734: addTransceiver does not check for missing rid properties
Spec has validation steps for rid properties that are present in sendEncodings, but does not have any validation steps related to encodings without a rid property. We want to allow rid to be absent when there is only one encoding, but if there is more than one encoding we need to throw (TypeError probably) if any of those encodings are missing a rid.

### PR DESCRIPTION
**Pull request by jan-ivar**
Fixes #2734.

***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webrtc-pc/pull/2774.html" title="Last updated on Oct 13, 2022, 12:46 AM UTC (aa415e9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-pc/2774/f1f465a...jan-ivar:aa415e9.html" title="Last updated on Oct 13, 2022, 12:46 AM UTC (aa415e9)">Diff</a>

### CODE REVIEW

**Comment by dontcallmedom** [comment]
`webrtc.js` needs to be updated to list `infra` in the `xref` property of `respecConfig` to have `map/contain` be recognized

**Review by youennf — APPROVED** [review]

**Comment by jan-ivar** [comment]
> `webrtc.js` needs to be updated to list `infra` in the `xref` property of `respecConfig` to have `map/contain` be recognized

Yes this PR and #2775 depend on #2772 which [adds this](https://github.com/w3c/webrtc-pc/pull/2772/files#diff-30884fa0da4ada2ba0368051a0dfe08ad79604262255a332c8712344cc35b851). Since we ran out of time today to merge the latter, I'll reshuffle the PRs to avoid this dependency.

**Comment by jan-ivar** [comment]
```
Error: Pull request 2774 not labeled as editorial and not referenced in amendments.json
```
Ok, so this is new. I need to rebase and add something to this file I assume? cc @dontcallmedom

**Comment by dontcallmedom** [comment]
thanks @jan-ivar for integrating the changes in amendments.json - indeed, the CI error is a recent addition to make sure we don't lose track of this.
FWIW, I had to tweak [a bit the change you made](https://github.com/w3c/webrtc-pc/commit/7666450321f7da266fa3a05e959869e906261ccf), since the id referenced in amendments.json needs to be for an element that contains the changes (you had picked the `<dt>` when the changes were in the `<dd>`); I'll try to see how to make it easier to review these amendment descriptions.

**Pull request merged**
