### PR TITLE
Effect of setting sender.track to null

### PR DESCRIPTION
**Pull request by aboba**
Fix for Issue https://github.com/w3c/webrtc-pc/issues/943

### CODE REVIEW

**Comment by aboba** [comment]
@taylor-b Looking through the specification, some methods allow sender.track to be null and others do not.  For example,   `addTransceiver` can be called with a  `kind` argument and no MediaStreamTrack, in which case  `transceiver.sender.track` would be null.  We have discussed whether PR https://github.com/w3c/webrtc-pc/pull/939 for `removeTrack` should set  `sender.track` to null.  So it seems reasonable to review `replaceTrack`.

**Comment by pthatcherg** [comment]
I think we should allow replaceTrack to take a null.  If it makes sense to
have an RtpSender without a track yet, it makes sense to be able to go from
having a track to not having a track.

**Comment by aboba** [comment]
@pthatcherg @taylor-b New issue opened to allow replaceTrack to take a null: https://github.com/w3c/webrtc-pc/issues/947

**Comment by aboba** [comment]
@vivienlacourba Looks like the build system is broken again.

**Comment by vivienlacourba** [comment]
@aboba travis and yarn don't play well together it seems. @marcoscaceres already reverted to using npm in respec and will hopefully soon publish a new release. For now I forced our CI to stick with respec v6.0.0

**Comment by marcoscaceres** [comment]
New released published. /me shakes fist at yarn 17.

**Comment by vivienlacourba** [comment]
and we are now back on respec's stable branch (v6.1.3)

**Pull request merged**
