### PR TITLE
pc.close() does not fire connectionstatechange either

### PR DESCRIPTION
**Pull request by fippo**
for ease of review expand to the bullet point above where this is copied from

***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-pc/pull/2461.html" title="Last updated on Feb 6, 2020, 1:19 PM UTC (5f9c341)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-pc/2461/539595f...fippo:5f9c341.html" title="Last updated on Feb 6, 2020, 1:19 PM UTC (5f9c341)">Diff</a>

### CODE REVIEW

**Comment by dontcallmedom** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by fippo** [comment]
@dontcallmedom you're fast as :zap:

**Comment by fippo** [comment]
test was here: https://github.com/web-platform-tests/wpt/pull/20703 ;-)

**Comment by fippo** [comment]
oh the same can be done a few steps earlier for signalingstate. Updated (please squash).
Any idea whether the two last steps should be done together with the signalingState?

**Pull request merged**
