### PR TITLE
Close peer connections (modulo firing ended) on page unload.

### PR DESCRIPTION
**Pull request by jan-ivar**
Fixes https://github.com/w3c/webrtc-pc/issues/2516.

cc @annevk in case I'm using the wrong hook here.

### CODE REVIEW

**Comment by annevk** [comment]
That looks reasonable, though I suspect we might want to eventually turn this into a thing where HTML calls an algorithm in WebRTC to ensure consistent ordering.

**Comment by jan-ivar** [comment]
@annevk there was some question about how this works with bfcache. Are pages even unloaded then? Safari apparently queuest a task to fire an ended event in these steps, and were hoping to see that task run on revival, e.g. if the user hits the back button.

**Comment by annevk** [comment]
They are, yes. As part of https://html.spec.whatwg.org/#unload-a-document. I'm not entirely convinced all of this is defined correctly though and interoperable across browsers.

**Comment by jan-ivar** [comment]
@youennf please file a follow-up if needed to fire the event on bfcache revival if you think it is not covered by this. We couldn't figure it out definitively one way or the other.

**Pull request merged**
