### PR TITLE
Have createOffer call addTransceiver() on offerToReceive.

### PR DESCRIPTION
**Pull request by jan-ivar**
Fix for https://github.com/w3c/webrtc-pc/issues/1383 and https://github.com/w3c/webrtc-pc/issues/1361

### CODE REVIEW

**Comment by fippo** [comment]
LGTM, thanks!

**Comment by aboba** [comment]
@ekr Can you review?

**Comment by aboba** [comment]
From https://www.w3.org/2017/06/28-webrtc-minutes

EKR to comment on the PR.

**Comment by aboba** [comment]
@ekr Can you review this?

**Comment by ekr** [comment]
None of this seems right. JSEP seems pretty clear that createOffer() doesn't modify the state of the PC. @juberti?

**Comment by stefhak** [comment]
I don't see this as createOffer() modifying state, but rather that when a user uses the legacy api ```offerToReceive``` they should really do ```addTrancseiver```, and the UA does it for the user (sort of a shim really).

This is is for legacy compatibility, and JSEP has removed everything about ```offerToReceive``` so I'm personally not overly concerned about aligning to the JSEP "spirit". I think this PR is a pragmatic way to add legacy compatibility we decided to do in a VI.

**Comment by aboba** [comment]
@stefhak Agree that on a browser that supports `addTransceiver` but not `offerToReceive`, `offerToReceive` could be implemented as a shim that called `addTransceiver`. 

This is also an argument for why `offerToReceive` is more of a convenience than a necessity.  Since there isn't an alternative way to support `offerToReceive` that creates `RtpSender`/`RtpReceiver` objects and all the methods that depend on them, if native support for `offerToReceive` is considered problematic, then the best alternative is probably to remove it from the spec and support it via shim if needed.


In fact, without an implicit call to `addTransceiver` it is not clear to me how to create RtpSender/RtpReceiver objects and enable methods referencing those objects to function as expected.

**Comment by stefhak** [comment]
@aboba I agree fully to what is said in https://github.com/w3c/webrtc-pc/pull/1430#issuecomment-327587494. However, to remove ```offerToReceove``` we would have to revert the decision to bring it back into the spec (remember it was gone for some time).

**Comment by jan-ivar** [comment]
@aboba I'm not seeing how the availability or ease of writing a shim makes a difference. Some sites will stop working (break), and would need manual intervention to resume working. AFAIK the triviality of intervention does not nullify web compat problems (or we wouldn't have nearly as many legacy APIs). Also, once we have a developer's attention, I'd rather they fix their code to call the new API directly than install some shim that perpetuates old modalities.

**Comment by stefhak** [comment]
Just connecting some (seemingly related) comments. I think https://github.com/w3c/webrtc-pc/issues/1383#issuecomment-327944759 is a response to https://github.com/w3c/webrtc-pc/pull/1430#issuecomment-327004905

**Comment by stefhak** [comment]
@jan-ivar I think you're perfectly right. But I was under the impression that many sites use the same shim, so that could have been a way to handle at least those. Anyway, I agree to that if we have the developer's attention we should get the to use transceivers instead.

**Comment by jan-ivar** [comment]
@stefhak If you're thinking of [adapter.js](https://github.com/webrtc/adapter), it generally shims new APIs on older browsers, not old APIs on new ones. Much like babel.js lets sites write es7+ without worrying about older browsers.
 
That's in some sense the opposite of a legacy shim that perpetuates old APIs: Move to adapter.js to write against the latest API, not the oldest API. It solves the legacy burden for people who keep up with the spec, while *browsers* handle the other group. The doc language on this being a "shim to insulate apps from spec changes" is a bit misleading. It generally insulates apps from browser differences, *if* you follow the spec.

For this reason, production sites are encouraged not to use [adapter-latest.js](https://webrtc.github.io/adapter/adapter-latest.js), which is generally the least stable version, not the most stable (nor do they like such runtime dependencies anyway, which works out well). Adapter.js has minted breaking major version updates at least a couple of times in the last couple of years to keep up with spec changes.

So it requires "developer attention" to update a production site's copy of adapter.js, which means it's of limited use to mitigate web compat problems.

**There are two exceptions**: Legacy APIs on Safari, and `createObjectURL(stream)`. The thinking here was that by transitioning support from browsers to adapter.js in a *minor* adapter release, it would move this breakage off individual browser release calendars, and onto the adapter.js major version update calendar. Kudos to the Safari team here.

I suppose we could attempt a similar exception for `offerToReceiveX`, *provided browsers commit to ending support*. Basically we need to follow through on it, and yank adapter support eventually in a major adapter version, after all browsers have yanked support.

Accumulating exceptions in adapter.js hurt its reputation as the spec-reference module. We've heard confusion already from people who think it's a "bloated legacy library" when it is anything but. We want sites to use adapter, which means keeping it lean and forward-thinking.

**Comment by stefhak** [comment]
@jan-ivar good points.

To re-iterate, the current decision is to have ```offerToReceive``` in the spec, and I personally think that with this PR merged we have it specced well enough. I hope we can get consensus to merge this PR and then be done with ```offerToReceive```.

**Pull request merged**
