### PR TITLE
Remove duplicate info on method parameters

### PR DESCRIPTION
**Pull request by dontcallmedom**
These were inherited from the previous respec WebIDL format, but they now represent a maintenance footgun

***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/webrtc-pc/noparamtables.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/webrtc-pc/cdf9e75...b0ac6f1.html)

### CODE REVIEW

**Comment by burnburn** [comment]
@dontcallmedom we should be consistent with gUM.  What do you think would be best to do that would give us consistency?

**Comment by dontcallmedom** [comment]
I think we should aim at this consistency, but that requires someone doing the work (not only for gum, but all the other specs who were converted); I'm happy to be assigned relevant issues in these other specs if no one else is available.

But in any case, I don't think we need to land these patches simultaneously - consistency over time is fine from my perspective.

**Comment by aboba** [comment]
@dontcallmedom Can you rebase this PR?

**Comment by dontcallmedom** [comment]
rebased

**Pull request merged**
