### PR TITLE
Update structured cloning for recent changes to HTML

### LINKED ISSUE #1089: Update for structured cloning changes in HTML
In https://github.com/whatwg/html/commit/97d644c97335956610a31e8ad98d1a388c063e84 we changed HTML's formulation of structured cloning significantly for the better. Web RTC should update to have separate serialization and deserialization steps. This can also eliminate having to deal with the memory variable.

I can work on a pull request for this shortly. Please let me know if there are any other Web RTC specs that have structured clone integration.

### PR DESCRIPTION
**Pull request by domenic**
Fixes #1089.

It'd be good for someone with domain knowledge that this makes sense as defined for the internal slots.

### CODE REVIEW

**Comment by alvestrand** [comment]
@henbos @martinthomson can you take a look?

**Comment by domenic** [comment]
Thanks, fixed!

**Comment by stefhak** [comment]
LGTM.

**Comment by stefhak** [comment]
@domenic : this PR was merged and then reverted via #1171. The reason for reverting was purely that we got pushback for referencing whatwg html (something we did already before, but it was detected now), and thus we reverted and referenced w3c html. I think everyone likes the new way to do "Safe passing of structured data" better, and I've raised an Issue on the html (5.2) spec (https://github.com/w3c/html/issues/898) to introduce it in the w3c version.

**Comment by domenic** [comment]
Welp, if there's a conflict between technical excellence and bureacracy, I can't help you there. I tried my best.

**Comment by stefhak** [comment]
We're grateful for that, and  hope we can sort out the bureaucracy soon!

**Pull request merged**
