### PR TITLE
Don't proceed w/removeTrack() if sender.track is already null.

### PR DESCRIPTION
**Pull request by jan-ivar**
Optimization.

***
[Preview](https://s3.amazonaws.com/pr-preview/jan-ivar/webrtc-pc/removetrack.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/webrtc-pc/c602d52...jan-ivar:ec20c9d.html)

### CODE REVIEW

**Comment by fippo** [comment]
without this
```
pc.replaceTrack(someSender);
pc.replaceTrack(someSender);
```
might have some unintended consequences (like firing ONN)

**Comment by taylor-b** [comment]
Fundamentally this isn't about ONN. It's more "don't change transceiver direction in `removeTrack` if sender's track is already `null`". So I'd suggest changing the PR description.

**Comment by aboba** [comment]
@jan-ivar Is there are issue associated with this PR?

**Comment by stefhak** [comment]
I think we could merge this one. There is some more discussion to be had (relation to #1390), but this PR in itself looks good.

**Comment by jan-ivar** [comment]
Hi, I'm back from a week off. This is unrelated to https://github.com/w3c/webrtc-pc/issues/1390. Sorry for the delay in answering and not filing a separate issue, as I thought it trivial (I was wrong)! 

First, I believe @fippo meant to write:
```js
pc.removeTrack(someSender);
pc.removeTrack(someSender);
```
I think he and I were confused by [current behavior](https://jsfiddle.net/jib1/ucvgcaox/) where the above fires ONN 3 (instead of 2!) times in Chrome (and fails for unrelated reasons in Firefox).

But @taylor-b is right, the [[[needNegotiation](http://w3c.github.io/webrtc-pc/#dfn-update-the-negotiation-needed-flag)]] internal slot already catches this; doesn't fire twice, so the spec was already fine here wrt ONN.

The remaining issue would be the implicit setting of direction. What should the following output?
```js
pc.removeTrack(transceiver.sender);
transceiver.setDirection("sendrecv");
pc.removeTrack(transceiver.sender);
console.log(transceiver.direction); // "recvonly" or "sendrecv" ?
```

**Comment by jan-ivar** [comment]
@fippo To clarify, with this PR merged, the 2nd `removeTrack` in my example skips remaining steps that used to (re)set `transceiver.direction`. It's now a no-op, leaving `"sendrecv"`.

**Comment by taylor-b** [comment]
> The remaining issue would be the implicit setting of direction. What should the following output?

That's the question. I can imagine arguments for either, but since this is a corner case and you can always just use `replaceTrack`/`setDirection` directly to get what you want, I think we just need to decide on _something_. Given the updated description, I'd be fine going with this.

**Pull request merged**
