### PR TITLE
fix offerToReceive(Audio|Video): false

### PR DESCRIPTION
**Pull request by fippo**
specifies that offerToReceive* stops all non-stopped transceivers from sending.

### CODE REVIEW

**Comment by fippo** [comment]
A stab at https://github.com/w3c/webrtc-pc/issues/1586

Ironically Firefox Nightly just "broke" this: https://jsfiddle.net/dyytbfxk/
is sendrecv in nightly, sendonly in stable.

Firefox stable sets (to my surprise) the direction on *all* m-lines.
This shows that this feature is 💩 💩 💩  :-)

**Comment by jan-ivar** [comment]
@fippo By "broke" you mean we now implement the spec as mandated?

**Comment by fippo** [comment]
given that the spec decided to change existing behaviour without even bothering to investigate usage (I have not seen httparchive usage data) yes.

It is very much unclear how many people depend on this and the lack of feedback from consumers of the peerconnection API (both service providers and opensource library vendors) is quite concerning.

**Comment by fippo** [comment]
needs rebase after #1686

**Pull request closed without merging**
