### PR TITLE
Rename updateIce() to setConfiguration() + Refactoring (move around some definitions)

### PR DESCRIPTION
**Pull request by adam-be**
This is a split PR #185 into three separate commits to make it easier to review.

It's based on the same rev as the original PR to make it easier to diff.

### CODE REVIEW

**Comment by adam-be** [comment]
Is this new name is fully compatible with how this method is defined to work? The name setConfiguration() sort of hints that it's this new configuration that must be used; nothing else. The old method, updateIce(), was defined to accept deltas and leaving members out would leave the corresponding setting unchanged.

If we want to keep the new name, it might be better to redefine its behavior.

Ping @juberti

**Comment by jan-ivar** [comment]
Agree it's unintuitive with the new name. It's probably better behavior as well - with precedent in track.applyConstraints (no partial apply) - and a good time to change it if we're going to change it.

**Comment by martinthomson** [comment]
Why can't this just say that this does a complete replacement of the configuration, or throws if that is not possible.  Doesn't this have to be asynchronous?  Can't this affect the operation of an outstanding `createOffer()`?

**Comment by jan-ivar** [comment]
I think that's the "better behavior" yes. It doesn't need to be asynchronous that I can see, and updateIce wasn't (it's implicitly "called" by the RTCPeerConnection constructor too).

If I change a wheel while I'm driving then I'm sure it has an effect. But since we're dealing with timing, I don't see how it needs to be deterministic.

**Comment by adam-be** [comment]
I'm leaning towards the replacement behavior as well. It' still easy to tweak the configuration by reading the current, changing it and doing a set.

**Comment by alvestrand** [comment]
@juberti do you agree that setConfiguration() overwrites the configuration no matter what, as suggested in bug #168 ?

**Comment by adam-be** [comment]
PR #213 replaces this one.

**Pull request closed without merging**
