### PR TITLE
webrtc.html: misprint and basic fixes

### PR DESCRIPTION
**Pull request by mparis**

### CODE REVIEW

**Comment by alvestrand** [comment]
@dontcallmedom can you check if the CLA bot is out of order?
I can't see a check done.
@mparis we have to check if your contribution meets the IPR rules, sorry about that.

**Comment by dontcallmedom** [comment]
@alvestrand re CI, @vivienlacourba and I are working on it

re IPR, this is purely editorial, so I don't think there should be any issue with merging

**Comment by alvestrand** [comment]
OK, we trust Dom on this.

**Comment by alvestrand** [comment]
(and thanks @mparis !)

**Comment by mparis** [comment]
You're welcome ;)

**Pull request merged**
