### PR TITLE
Updating build configuration

### PR DESCRIPTION
**Pull request by martinthomson**
This depends on w3c/webrtc-respec-ci#6.  I will add a bogus commit to test that it works on this branch first, then I will await the landing of the dependency.

### CODE REVIEW

**Comment by dontcallmedom** [comment]
https://github.com/w3c/webrtc-respec-ci/pull/6 has now been merged

**Comment by martinthomson** [comment]
I rebased to latest, ran `make tidy`.  This probably needs to be merged promptly to avoid clobbering any changes that happened in the meantime. The commit that this is based on is 5e02dab573831d612a84eb882d5fdfd4067f4fd4 .

**Comment by alvestrand** [comment]
If Dom likes this, please merge it.

**Comment by martinthomson** [comment]
If you keep picking at it, it will never heal.

**Comment by alvestrand** [comment]
It's software. Stability is death.

**Comment by dontcallmedom** [comment]
Closing this one in favor of (identical but without linewrapping) #487

**Pull request closed without merging**
