### PR TITLE
replace "a RTCsomething" with "an RTCsomething"

### PR DESCRIPTION
**Pull request by fippo**
for consistency

***
[Preview](https://s3.amazonaws.com/pr-preview/fippo/webrtc-pc/arrrr-like-a-pirate.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/webrtc-pc/7d5b589...fippo:1be6828.html)

### CODE REVIEW

**Comment by fippo** [comment]
note: this doesn't replace the issue in #1525 where I initially found this

**Comment by stefhak** [comment]
lgtm.

**Comment by burnburn** [comment]
Editors can integrate when least likely to break other PRs.

**Comment by aboba** [comment]
@fippo Can you rebase?

**Comment by fippo** [comment]
rebased

**Pull request merged**
