### PR TITLE
Make DataChannels Transferable and explain the implications

### PR DESCRIPTION
**Pull request by ekr**
@martinthomson PTAL

### CODE REVIEW

**Comment by stefhak** [comment]
The actual transfer algorithm is not described. Look at e.g. https://html.spec.whatwg.org/multipage/scripting.html#transferCanvasProxy or https://html.spec.whatwg.org/multipage/comms.html#transferMessagePort (the transfer for ArrayBuffer also describes some error handling for the case when the ArrayBuffer was already neutered).

**Comment by alvestrand** [comment]
Tagging @annevk because I think the comment originated from him.

**Comment by annevk** [comment]
Yeah, you will need to define what transferring actually means (presumably you create a new instance within the other realm and move internal slot) and how it affects the original object (presumably some operations will start failing). https://github.com/whatwg/html/pull/444 has another example of an object that is being made transferable.

**Comment by stefhak** [comment]
This PR (and #317 ) needs work. If no one does the work it can't be part of 1.0.

**Comment by alvestrand** [comment]
Closing while preparing for 1.0. It can be reopened later.

**Pull request closed without merging**
