### PR TITLE
Definition of Active for an RTCRtpReceiver

### PR DESCRIPTION
**Pull request by aboba**
Fix for Issue https://github.com/w3c/webrtc-pc/issues/473

### CODE REVIEW

**Comment by alvestrand** [comment]
Pinging @pthatcherg

**Comment by elagerway** [comment]
@pthatcherg another one for you?

**Comment by pthatcherg** [comment]
LGTM

**Comment by aboba** [comment]
@pthatcherg - It is not clear to me that this PR is sufficient.  Could you comment on some of the other aspects raised in the post below (such as whether we need a getParameters() method in RTCRtpReceiver)? 
https://lists.w3.org/Archives/Public/public-webrtc/2016Feb/0029.html

**Comment by pthatcherg** [comment]
Ah, I see.

I think getParameters() on RTCRtpReceiver makes sense.

**Comment by aboba** [comment]
@ptatcherg PR https://github.com/w3c/webrtc-pc/pull/504 adds getParameters() to the RTCRtpReceiver. I have also submitted PR https://github.com/w3c/webrtc-pc/pull/505 to add activateReceiver() to the RTCRtpTransceiver. 

Can you review these PRs to make sure they make sense?

**Comment by aboba** [comment]
Removing "Assignee action" on this PR, since Peter has reviewed it.

**Pull request merged**
