### PR TITLE
Specify behavior if browser doesn't implement "negotiate" rtcpMuxPolicy.

### LINKED ISSUE #1065: Need to specify what happens if the browser doesn't implement "negotiate" rtcpMuxPolicy
JSEP states:

> Implementations MAY choose to reject attempts by the application to set the multiplexing policy to "negotiate".

So, what does this mean at the API level? A "NotSupportedError" being thrown by the RTCPeerConnection constructor?

### PR DESCRIPTION
**Pull request by taylor-b**
Fixes #1065.

Also moved some steps around in the RTCPeerConnection constructor
steps, such that everything dealing with the RTCConfiguration is in one
place.

### CODE REVIEW

**Comment by aboba** [comment]
getConfiguration() obtains the configuration from the configuration internal slot, so I don't think you can delete storing the configuration in the configuration internal slot in lines 571 through 574.

**Comment by taylor-b** [comment]
@aboba The "set the configuration" steps already do this though, so it was redundant.

**Comment by stefhak** [comment]
LGTM.

**Comment by taylor-b** [comment]
JSEP reference has been fixed. Ok to merge?

**Pull request merged**
