### PR TITLE
Remove RTCPeerConnection.createDTMFSender and add RTCRtpSender.dtmf.

### PR DESCRIPTION
**Pull request by pthatcherg**
Fixing https://github.com/w3c/webrtc-pc/issues/132

### CODE REVIEW

**Comment by alvestrand** [comment]
Needs to be integrated after #175, since it references RTCRTPSender.

**Comment by fluffy** [comment]
Need to think about how this interacts with SDP - Will all tracks have DTMF negotiated for them ? seems like a waste of PT when it is usually not needed.

**Comment by pthatcherg** [comment]
Cullen:  Would it make sense to have an option in RTCOfferAnwerOptions.dtmf just as we have RTCOfferAnswerOptions.voiceActivityDetection in https://github.com/pthatcherg/webrtc-pc/commit/90af82e02dc141d83048a8497fae5fe4fb365f68?

If that would work, I can propose it on the list.

**Comment by pthatcherg** [comment]
In Chrome at least, we always put DTMF in the offer, so we're already using
the PT.   Meanwhile, we're always negotiating PCMA and PCMU.  In other
words, we're already using lots of PTs.  Meanwhile, is it even possible to
re-negotiate with DTMF later if the DTMF isn't in the original offer?  In
that case, we have to have it in the original offer anyway.

**Comment by fluffy** [comment]
OK - seems reasonable to me

**Comment by adam-be** [comment]
Rebased and integrated.

**Comment by jesup** [comment]
I"ll note that Firefox has not thus far added DTMF to our offers (nor have we integrated support for it yet).  If we're requiring DTMF on all audio channels, that's new - IMHO it should be in OfferAnswerOptions

**Pull request closed without merging**
