### PR TITLE
ensure valid markup

### PR DESCRIPTION
**Pull request by dontcallmedom**

### CODE REVIEW

**Comment by burnburn** [comment]
I'm fine with these changes.  Do we need Travis to be happy?

**Comment by dontcallmedom** [comment]
Travis will be happy when #180 is merged in (assuming no other markup errors have been introduced in the meantime)

**Comment by adam-be** [comment]
@dontcallmedom, can you take a look at this one please.

**Comment by dontcallmedom** [comment]
@adam-be the failure is expected given the state of the markup on which this PR is merged; this shouldn't prevent us from merging (the goal is to detect these failures moving forward)

**Pull request merged**
