### PR TITLE
Various editorial fixes

### PR DESCRIPTION
**Pull request by dontcallmedom**
(spotted when preparing the doc for publication as TR WD)

### CODE REVIEW

**Comment by fluffy** [comment]
I guess this need to be rebased but teh changes all LGTM

**Comment by burnburn** [comment]
@dontcallmedom I don't understand the createOffer/createAnswer link changes.  The new values don't look correct to me.  Everything else looks fine.

**Comment by dontcallmedom** [comment]
@burnburn I had gotten one of the links wrong, which I've now fixed; I think they are now correct.

**Comment by burnburn** [comment]
This is fine now.  Thanks.

**Comment by burnburn** [comment]
@dontcallmedom can you please rebase?  I started merging manually but it's a bit confusing in places.

**Comment by adam-be** [comment]
Sadly, we have left this PR to rot and it's a bit tricky to merge. @dontcallmedom, can you update it please?

**Comment by dontcallmedom** [comment]
will look at it

**Comment by dontcallmedom** [comment]
should be good now

**Comment by adam-be** [comment]
Thanks for rebasing.

We've got feedback [1] on the Media Capture and streams draft that we shouldn't refer to JS functions directly from algorithms, but let's fix that later.

[1] https://github.com/w3c/mediacapture-main/issues/158

**Pull request merged**
