### PR TITLE
Support ufrag in IceCandidate and end of IceCandidate indicator 

### LINKED ISSUE #726: Add a ufrag attribute to the RTCIceCandidate structure to indicate which ICE context
At IETF 95, we agreed that we should have the ufrag included with ICE candidates so you could disambiguate candidates and end-of-candidates from different ICE generations (restarts). We should
1. Add ufrag to RTCIceCandidate
2. Add ufrag to one of the things that the serializer emits

We should also consider modifying the "done gathering marker" to be not RTCIceCandidate = null but rather RTCIceCandidate = { mid, null} or something.

### PR DESCRIPTION
**Pull request by fluffy**
Fixes #726

### CODE REVIEW

**Comment by fluffy** [comment]
In the current spec,  the end of candidates are indicated by a NULL, this changes this to return a map with the ufrag. It is not clear to me how to make this backwards compatible.

**Comment by fluffy** [comment]
based on call today - still return the NULL at end of all candidates, but also send per mid end of candidates in a separate event.

**Comment by fluffy** [comment]
Change PR to just do ufrag to ice candidate for now and worry about separate issue of what happened on end of candidates on separate bug to be filed.

**Comment by alvestrand** [comment]
@fluffy are you intending to do the change indicated in the comment above, or are you waiting for someone else to do it?

**Comment by alvestrand** [comment]
This was discussed at TPAC, but I don't think we ended up with a complete solution. Is this a partial solution we should merge anyway, or do we wait for a final one? @pthatcherg pinged.

**Comment by stefhak** [comment]
Pinging @pthatcherg again. Any comment?

**Comment by alvestrand** [comment]
Obsoleted by #968

**Pull request closed without merging**
